# Generated by Django 4.2.20 on 2025-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
